#############################################################################
# Makefile for building: ogr2gui
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  ogr2gui.pro
# Template: app
# Command: E:/QtSDK-i686/bin/qmake.exe -spec win32-g++ CONFIG+=release -o Makefile ogr2gui.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:/QtSDK-i686/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ogr2gui.pro E:/QtSDK-i686/mkspecs/win32-g++/qmake.conf E:/QtSDK-i686/mkspecs/features/spec_pre.prf \
		E:/QtSDK-i686/mkspecs/qdevice.pri \
		E:/QtSDK-i686/mkspecs/features/device_config.prf \
		E:/QtSDK-i686/mkspecs/common/shell-unix.conf \
		E:/QtSDK-i686/mkspecs/qconfig.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axbase.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axserver.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_clucene_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_concurrent.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_core.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_core_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_dbus.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_declarative.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_declarative_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_designer.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_designer_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_gui.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_gui_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_help.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_help_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_multimedia.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_network.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_network_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_nfc.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_opengl.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_platformsupport_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_positioning.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_printsupport.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qml.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qml_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qmltest.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_quick.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_quick_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_script.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_script_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_scripttools.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_sensors.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_serialport.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_sql.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_sql_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_svg.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_svg_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_testlib.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_uitools.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_webkit.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_webkit_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_webkitwidgets.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_widgets.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_winextras.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_xml.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_xml_private.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/QtSDK-i686/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/QtSDK-i686/mkspecs/features/qt_functions.prf \
		E:/QtSDK-i686/mkspecs/features/qt_config.prf \
		E:/QtSDK-i686/mkspecs/win32-g++/qmake.conf \
		E:/QtSDK-i686/mkspecs/features/spec_post.prf \
		E:/QtSDK-i686/mkspecs/features/exclusive_builds.prf \
		E:/QtSDK-i686/mkspecs/features/default_pre.prf \
		E:/QtSDK-i686/mkspecs/features/win32/default_pre.prf \
		E:/QtSDK-i686/mkspecs/features/resolve_config.prf \
		E:/QtSDK-i686/mkspecs/features/exclusive_builds_post.prf \
		E:/QtSDK-i686/mkspecs/features/default_post.prf \
		E:/QtSDK-i686/mkspecs/features/win32/rtti.prf \
		E:/QtSDK-i686/mkspecs/features/warn_on.prf \
		E:/QtSDK-i686/mkspecs/features/qt.prf \
		E:/QtSDK-i686/mkspecs/features/resources.prf \
		E:/QtSDK-i686/mkspecs/features/moc.prf \
		E:/QtSDK-i686/mkspecs/features/win32/opengl.prf \
		E:/QtSDK-i686/mkspecs/features/uic.prf \
		E:/QtSDK-i686/mkspecs/features/win32/windows.prf \
		E:/QtSDK-i686/mkspecs/features/testcase_targets.prf \
		E:/QtSDK-i686/mkspecs/features/exceptions.prf \
		E:/QtSDK-i686/mkspecs/features/yacc.prf \
		E:/QtSDK-i686/mkspecs/features/lex.prf \
		ogr2gui.pro \
		E:/QtSDK-i686/lib/Qt5Widgets.prl \
		E:/QtSDK-i686/lib/Qt5Sql.prl \
		E:/QtSDK-i686/lib/Qt5Gui.prl \
		E:/QtSDK-i686/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ CONFIG+=release -o Makefile ogr2gui.pro
E:/QtSDK-i686/mkspecs/features/spec_pre.prf:
E:/QtSDK-i686/mkspecs/qdevice.pri:
E:/QtSDK-i686/mkspecs/features/device_config.prf:
E:/QtSDK-i686/mkspecs/common/shell-unix.conf:
E:/QtSDK-i686/mkspecs/qconfig.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axbase.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axbase_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axcontainer.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axserver.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_axserver_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_bluetooth.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_clucene_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_concurrent.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_core.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_core_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_dbus.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_dbus_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_declarative.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_declarative_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_designer.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_designer_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_gui.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_gui_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_help.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_help_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_multimedia.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_network.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_network_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_nfc.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_nfc_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_opengl.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_opengl_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_openglextensions.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_platformsupport_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_positioning.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_positioning_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_printsupport.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qml.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qml_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qmltest.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_quick.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_quick_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_script.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_script_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_scripttools.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_sensors.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_sensors_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_serialport.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_serialport_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_sql.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_sql_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_svg.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_svg_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_testlib.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_testlib_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_uitools.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_uitools_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_webkit.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_webkit_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_webkitwidgets.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_widgets.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_widgets_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_winextras.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_winextras_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_xml.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_xml_private.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/QtSDK-i686/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/QtSDK-i686/mkspecs/features/qt_functions.prf:
E:/QtSDK-i686/mkspecs/features/qt_config.prf:
E:/QtSDK-i686/mkspecs/win32-g++/qmake.conf:
E:/QtSDK-i686/mkspecs/features/spec_post.prf:
E:/QtSDK-i686/mkspecs/features/exclusive_builds.prf:
E:/QtSDK-i686/mkspecs/features/default_pre.prf:
E:/QtSDK-i686/mkspecs/features/win32/default_pre.prf:
E:/QtSDK-i686/mkspecs/features/resolve_config.prf:
E:/QtSDK-i686/mkspecs/features/exclusive_builds_post.prf:
E:/QtSDK-i686/mkspecs/features/default_post.prf:
E:/QtSDK-i686/mkspecs/features/win32/rtti.prf:
E:/QtSDK-i686/mkspecs/features/warn_on.prf:
E:/QtSDK-i686/mkspecs/features/qt.prf:
E:/QtSDK-i686/mkspecs/features/resources.prf:
E:/QtSDK-i686/mkspecs/features/moc.prf:
E:/QtSDK-i686/mkspecs/features/win32/opengl.prf:
E:/QtSDK-i686/mkspecs/features/uic.prf:
E:/QtSDK-i686/mkspecs/features/win32/windows.prf:
E:/QtSDK-i686/mkspecs/features/testcase_targets.prf:
E:/QtSDK-i686/mkspecs/features/exceptions.prf:
E:/QtSDK-i686/mkspecs/features/yacc.prf:
E:/QtSDK-i686/mkspecs/features/lex.prf:
ogr2gui.pro:
E:/QtSDK-i686/lib/Qt5Widgets.prl:
E:/QtSDK-i686/lib/Qt5Sql.prl:
E:/QtSDK-i686/lib/Qt5Gui.prl:
E:/QtSDK-i686/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=release -o Makefile ogr2gui.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
