#############################################################################
# Makefile for building: ogr2gui
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sat Oct 31 13:16:13 2009
# Project:  ogr2gui.pro
# Template: app
# Command: c:\Qt\2009.03\qt\bin\qmake.exe -win32 -o Makefile ogr2gui.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/Qt/2009.03/qt/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ogr2gui.pro  ../../qt/2009.03/qt/mkspecs/default/qmake.conf ../../qt/2009.03/qt/mkspecs/qconfig.pri \
		../../qt/2009.03/qt/mkspecs/features/qt_functions.prf \
		../../qt/2009.03/qt/mkspecs/features/qt_config.prf \
		../../qt/2009.03/qt/mkspecs/features/exclusive_builds.prf \
		../../qt/2009.03/qt/mkspecs/features/default_pre.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/default_pre.prf \
		../../qt/2009.03/qt/mkspecs/features/release.prf \
		../../qt/2009.03/qt/mkspecs/features/debug_and_release.prf \
		../../qt/2009.03/qt/mkspecs/features/default_post.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/default_post.prf \
		../../qt/2009.03/qt/mkspecs/features/static.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/rtti.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/exceptions_off.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/stl.prf \
		../../qt/2009.03/qt/mkspecs/features/warn_on.prf \
		../../qt/2009.03/qt/mkspecs/features/qt.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/thread.prf \
		../../qt/2009.03/qt/mkspecs/features/moc.prf \
		../../qt/2009.03/qt/mkspecs/features/win32/windows.prf \
		../../qt/2009.03/qt/mkspecs/features/resources.prf \
		../../qt/2009.03/qt/mkspecs/features/uic.prf \
		../../qt/2009.03/qt/mkspecs/features/yacc.prf \
		../../qt/2009.03/qt/mkspecs/features/lex.prf \
		../../qt/2009.03/qt/mkspecs/features/include_source_dir.prf \
		c:/qt/2009.03/qt/lib/qtmain.prl \
		c:/qt/2009.03/qt/lib/QtSql.prl \
		c:/qt/2009.03/qt/lib/QtGui.prl \
		c:/qt/2009.03/qt/lib/QtCore.prl
	$(QMAKE) -win32 -o Makefile ogr2gui.pro
../../qt/2009.03/qt/mkspecs/qconfig.pri:
../../qt/2009.03/qt/mkspecs/features/qt_functions.prf:
../../qt/2009.03/qt/mkspecs/features/qt_config.prf:
../../qt/2009.03/qt/mkspecs/features/exclusive_builds.prf:
../../qt/2009.03/qt/mkspecs/features/default_pre.prf:
../../qt/2009.03/qt/mkspecs/features/win32/default_pre.prf:
../../qt/2009.03/qt/mkspecs/features/release.prf:
../../qt/2009.03/qt/mkspecs/features/debug_and_release.prf:
../../qt/2009.03/qt/mkspecs/features/default_post.prf:
../../qt/2009.03/qt/mkspecs/features/win32/default_post.prf:
../../qt/2009.03/qt/mkspecs/features/static.prf:
../../qt/2009.03/qt/mkspecs/features/win32/rtti.prf:
../../qt/2009.03/qt/mkspecs/features/win32/exceptions_off.prf:
../../qt/2009.03/qt/mkspecs/features/win32/stl.prf:
../../qt/2009.03/qt/mkspecs/features/warn_on.prf:
../../qt/2009.03/qt/mkspecs/features/qt.prf:
../../qt/2009.03/qt/mkspecs/features/win32/thread.prf:
../../qt/2009.03/qt/mkspecs/features/moc.prf:
../../qt/2009.03/qt/mkspecs/features/win32/windows.prf:
../../qt/2009.03/qt/mkspecs/features/resources.prf:
../../qt/2009.03/qt/mkspecs/features/uic.prf:
../../qt/2009.03/qt/mkspecs/features/yacc.prf:
../../qt/2009.03/qt/mkspecs/features/lex.prf:
../../qt/2009.03/qt/mkspecs/features/include_source_dir.prf:
c:\qt\2009.03\qt\lib\qtmain.prl:
c:\qt\2009.03\qt\lib\QtSql.prl:
c:\qt\2009.03\qt\lib\QtGui.prl:
c:\qt\2009.03\qt\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile ogr2gui.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
